name: tms_prophet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.1.4
  - numpy=1.24.3
  - matplotlib=3.7.3
  - seaborn=0.13.0
  - scikit-learn=1.3.2
  - jupyter=1.0.0
  - pip=23.1.2
  - pip:
    - prophet==1.1.4
    - plotly==5.18.0
    - yfinance==0.2.33
    - requests==2.31.0
